name: xzitpocket
description: "掌上徐工"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  pointycastle: ^3.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.8.1
  shared_preferences: ^2.3.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
